// OSRS quest catalog used for seeding and for ordering/grouping in the UI.
// The plugin syncs live quest states by name (RuneLite Quest enum), so this
// list only needs to cover display grouping — unknown quests still render.

export const F2P_QUESTS = [
  "Below Ice Mountain",
  "Black Knights' Fortress",
  "Cook's Assistant",
  "The Corsair Curse",
  "Demon Slayer",
  "Doric's Quest",
  "Dragon Slayer I",
  "Ernest the Chicken",
  "Goblin Diplomacy",
  "Imp Catcher",
  "The Knight's Sword",
  "Misthalin Mystery",
  "Pirate's Treasure",
  "Prince Ali Rescue",
  "The Restless Ghost",
  "Romeo & Juliet",
  "Rune Mysteries",
  "Sheep Shearer",
  "Shield of Arrav",
  "Sleeping Giants",
  "Vampyre Slayer",
  "Witch's Potion",
  "X Marks the Spot",
] as const;

export const P2P_QUESTS = [
  "Animal Magnetism",
  "Another Slice of H.A.M.",
  "At First Light",
  "Beneath Cursed Sands",
  "Between a Rock...",
  "Big Chompy Bird Hunting",
  "Biohazard",
  "Bone Voyage",
  "The Blood Moon Rises",
  "Cabin Fever",
  "Children of the Sun",
  "Clock Tower",
  "Cold War",
  "Contact!",
  "Creature of Fenkenstrain",
  "The Curse of Arrav",
  "Darkness of Hallowvale",
  "Death Plateau",
  "Death on the Isle",
  "Defender of Varrock",
  "The Depths of Despair",
  "Desert Treasure I",
  "Desert Treasure II - The Fallen Empire",
  "Devious Minds",
  "The Dig Site",
  "Dragon Slayer II",
  "Dream Mentor",
  "Druidic Ritual",
  "Dwarf Cannon",
  "Eadgar's Ruse",
  "Eagles' Peak",
  "Elemental Workshop I",
  "Elemental Workshop II",
  "Enakhra's Lament",
  "Enlightened Journey",
  "Ethically Acquired Antiquities",
  "The Eyes of Glouphrie",
  "Fairytale I - Growing Pains",
  "Fairytale II - Cure a Queen",
  "Family Crest",
  "The Feud",
  "Fight Arena",
  "Fishing Contest",
  "Forgettable Tale...",
  "The Forsaken Tower",
  "The Fremennik Exiles",
  "The Fremennik Isles",
  "The Fremennik Trials",
  "Garden of Tranquillity",
  "Gertrude's Cat",
  "Getting Ahead",
  "Ghosts Ahoy",
  "The Giant Dwarf",
  "The Golem",
  "The Grand Tree",
  "The Great Brain Robbery",
  "Grim Tales",
  "The Hand in the Sand",
  "Haunted Mine",
  "Hazeel Cult",
  "Heroes' Quest",
  "His Faithful Servants",
  "Holy Grail",
  "Horror from the Deep",
  "Icthlarin's Little Helper",
  "In Aid of the Myreque",
  "In Search of Knowledge",
  "In Search of the Myreque",
  "Jungle Potion",
  "King's Ransom",
  "A Kingdom Divided",
  "Land of the Goblins",
  "Legends' Quest",
  "Lost City",
  "The Lost Tribe",
  "Lunar Diplomacy",
  "Making Friends with My Arm",
  "Making History",
  "Meat and Greet",
  "Merlin's Crystal",
  "Monkey Madness I",
  "Monkey Madness II",
  "Monk's Friend",
  "Mountain Daughter",
  "Mourning's End Part I",
  "Mourning's End Part II",
  "Murder Mystery",
  "My Arm's Big Adventure",
  "Nature Spirit",
  "A Night at the Theatre",
  "Observatory Quest",
  "Olaf's Quest",
  "One Small Favour",
  "The Path of Glouphrie",
  "Perilous Moons",
  "Plague City",
  "A Porcine of Interest",
  "Priest in Peril",
  "The Queen of Thieves",
  "Rag and Bone Man I",
  "Rag and Bone Man II",
  "Ratcatchers",
  "Recipe for Disaster",
  "Recruitment Drive",
  "Regicide",
  "The Ribbiting Tale of a Lily Pad Labour Dispute",
  "Roving Elves",
  "Royal Trouble",
  "Rum Deal",
  "Scorpion Catcher",
  "Sea Slug",
  "Secrets of the North",
  "Shades of Mort'ton",
  "Shadow of the Storm",
  "Sheep Herder",
  "Shilo Village",
  "Sins of the Father",
  "The Slug Menace",
  "Song of the Elves",
  "A Soul's Bane",
  "Spirits of the Elid",
  "Swan Song",
  "Tai Bwo Wannai Trio",
  "A Tail of Two Cats",
  "Tale of the Righteous",
  "A Taste of Hope",
  "Tears of Guthix",
  "Temple of Ikov",
  "Temple of the Eye",
  "Throne of Miscellania",
  "The Tourist Trap",
  "Tower of Life",
  "Tree Gnome Village",
  "Tribal Totem",
  "Troll Romance",
  "Troll Stronghold",
  "Twilight's Promise",
  "Underground Pass",
  "Wanted!",
  "Watchtower",
  "Waterfall Quest",
  "What Lies Below",
  "While Guthix Sleeps",
  "Witch's House",
  "Zogre Flesh Eaters",
] as const;

export const ALL_QUESTS: string[] = [...F2P_QUESTS, ...P2P_QUESTS];

// Miniquests as synced from RuneLite's quest list (names per the OSRS wiki).
// They award no quest points and never gate the Quest point cape — critical
// when reasoning about quest completion.
export const MINIQUESTS = [
  "Alfred Grimhand's Barcrawl",
  "Barbarian Training",
  "Bear Your Soul",
  "Curse of the Empty Lord",
  "Daddy's Home",
  "The Enchanted Key",
  "Enter the Abyss",
  "Family Pest",
  "The Frozen Door",
  "The General's Shadow",
  "His Faithful Servants",
  "Hopespear's Will",
  "In Search of Knowledge",
  "Into the Tombs",
  "Lair of Tarn Razorlor",
  "The Lair of Tarn Razorlorn", // RuneLite's spelling
  "Mage Arena I",
  "The Mage Arena", // RuneLite's spelling
  "Mage Arena II",
  "The Mage Arena II", // RuneLite's spelling
  "Skippy and the Mogres",
  "Vale Totems",
] as const;

// Sources spell these inconsistently ("The Lair of Tarn Razorlorn",
// "Mage Arena" vs "The Mage Arena") — normalize before comparing.
function questKey(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/^the /, "")
    .trim();
}

const MINIQUEST_KEYS = new Set(MINIQUESTS.map(questKey));

export function isMiniquest(name: string): boolean {
  return MINIQUEST_KEYS.has(questKey(name));
}

export const DIARY_AREAS = [
  "Ardougne",
  "Desert",
  "Falador",
  "Fremennik",
  "Kandarin",
  "Karamja",
  "Kourend & Kebos",
  "Lumbridge & Draynor",
  "Morytania",
  "Varrock",
  "Western Provinces",
  "Wilderness",
] as const;

export const DIARY_TIERS = ["EASY", "MEDIUM", "HARD", "ELITE"] as const;
